.PHONY: clean All

All:
	@echo "----------Building project:[ ET4 - Debug ]----------"
	@cd "/home/atte/MEGA/Tiedostot/Koulu/OOJ/ooj-2019-008/et4" && "$(MAKE)" -f  "ET4.mk"
clean:
	@echo "----------Cleaning project:[ ET4 - Debug ]----------"
	@cd "/home/atte/MEGA/Tiedostot/Koulu/OOJ/ooj-2019-008/et4" && "$(MAKE)" -f  "ET4.mk" clean
